version: '3'

services:

  varnish:
    build: ./varnish
    ports:
      - 8000:80
    networks:
      - frontend
      - backend

  command-frontend:
    hostname: command-frontend
    build: ./command-frontend
    networks:
      - frontend
      - backend

  command-backend:
    hostname: command-backend
    build: ./command-backend
    networks:
      - backend

  query-frontend:
    hostname: query-frontend
    build: ./query-frontend
    networks:
      - frontend
      - backend

  query-backend:
    hostname: query-backend
    build: ./query-backend
    networks:
      - backend

networks:
  frontend:
  backend: